#!/bin/bash
# Regenerate catalogues: compatibility table + web catalogue + Firestore publish

set -e

cd "$(dirname "$0")/.."

echo "🔄 Regenerating A2UI catalogues..."
echo ""

# 1. Update reference file (a2ui-catalogue.md)
echo "  [1/2] Generating compatibility table → a2ui-catalogue.md"
python3 tests/generate_compat_table.py > a2ui-catalogue.md
echo "    ✅ Reference file updated"

# 2. Publish to Firestore
echo "  [2/2] Publishing to Firestore..."
python3 scripts/publish_catalogue.py

echo ""
echo "✨ All catalogues regenerated"

# 3. Stage changes for auto-commit
if [ -n "$GIT_AUTO_COMMIT" ]; then
    echo ""
    echo "📝 Auto-committing changes..."
    git add a2ui-catalogue.md
    if git diff --cached --quiet; then
        echo "  No changes to commit"
    else
        git commit -m "chore: regenerate A2UI catalogues from schema.yaml" \
            -m "- Updated compatibility reference table (a2ui-catalogue.md)" \
            -m "- Published web catalogue to Firestore (topic: a2ui)" \
            -m "- Auto-generated by post-commit hook"
        echo "    ✅ Committed"
    fi
fi
